"""initial_schema

Revision ID: 61b94d732ada
Revises:
Create Date: 2026-09-07 14:49:50.771444
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '61b94d732ada'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('protocol', sa.String(length=24), nullable=False),
    sa.Column('transport', sa.String(length=24), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('security', sa.String(length=24), nullable=False),
    sa.Column('sni', sa.String(length=255), nullable=False),
    sa.Column('websocket_host', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('fingerprint', sa.String(length=32), nullable=False),
    sa.Column('alpn', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('internal_port', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_enabled'), 'nodes', ['enabled'], unique=False)
    op.create_index(op.f('ix_nodes_slug'), 'nodes', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('quota_bytes', sa.Integer(), nullable=False),
    sa.Column('used_up_bytes', sa.Integer(), nullable=False),
    sa.Column('used_down_bytes', sa.Integer(), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_ips', sa.Integer(), nullable=False),
    sa.Column('speed_limit_bps', sa.Integer(), nullable=False),
    sa.Column('subscription_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_active'), 'users', ['active'], unique=False)
    op.create_index(op.f('ix_users_expires_at'), 'users', ['expires_at'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('access_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('credential', sa.String(length=255), nullable=False),
    sa.Column('secret_payload', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_keys_credential'), 'access_keys', ['credential'], unique=False)
    op.create_index(op.f('ix_access_keys_node_id'), 'access_keys', ['node_id'], unique=False)
    op.create_index(op.f('ix_access_keys_user_id'), 'access_keys', ['user_id'], unique=False)
    op.create_index('ix_access_keys_user_node', 'access_keys', ['user_id', 'node_id'], unique=True)
    op.create_table('admin_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_sessions_admin_id'), 'admin_sessions', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_sessions_expires_at'), 'admin_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_admin_sessions_token_hash'), 'admin_sessions', ['token_hash'], unique=True)
    op.create_table('connection_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('gateway_instance', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('close_reason', sa.String(length=255), nullable=False),
    sa.Column('uplink_bytes', sa.Integer(), nullable=False),
    sa.Column('downlink_bytes', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connection_sessions_last_seen_at'), 'connection_sessions', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_connection_sessions_node_id'), 'connection_sessions', ['node_id'], unique=False)
    op.create_index(op.f('ix_connection_sessions_source_ip'), 'connection_sessions', ['source_ip'], unique=False)
    op.create_index(op.f('ix_connection_sessions_status'), 'connection_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_connection_sessions_user_id'), 'connection_sessions', ['user_id'], unique=False)
    op.create_index('ix_sessions_user_active', 'connection_sessions', ['user_id', 'ended_at', 'last_seen_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_user_active', table_name='connection_sessions')
    op.drop_index(op.f('ix_connection_sessions_user_id'), table_name='connection_sessions')
    op.drop_index(op.f('ix_connection_sessions_status'), table_name='connection_sessions')
    op.drop_index(op.f('ix_connection_sessions_source_ip'), table_name='connection_sessions')
    op.drop_index(op.f('ix_connection_sessions_node_id'), table_name='connection_sessions')
    op.drop_index(op.f('ix_connection_sessions_last_seen_at'), table_name='connection_sessions')
    op.drop_table('connection_sessions')
    op.drop_index(op.f('ix_admin_sessions_token_hash'), table_name='admin_sessions')
    op.drop_index(op.f('ix_admin_sessions_expires_at'), table_name='admin_sessions')
    op.drop_index(op.f('ix_admin_sessions_admin_id'), table_name='admin_sessions')
    op.drop_table('admin_sessions')
    op.drop_index('ix_access_keys_user_node', table_name='access_keys')
    op.drop_index(op.f('ix_access_keys_user_id'), table_name='access_keys')
    op.drop_index(op.f('ix_access_keys_node_id'), table_name='access_keys')
    op.drop_index(op.f('ix_access_keys_credential'), table_name='access_keys')
    op.drop_table('access_keys')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_expires_at'), table_name='users')
    op.drop_index(op.f('ix_users_active'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_nodes_slug'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_enabled'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
